// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvS2ZO6EAkQ9KHw5TEX9vxZsu1CoIikwE',
    appId: '1:230612083597:web:c426da22da060bf6e313c4',
    messagingSenderId: '230612083597',
    projectId: 'e-commerce1-e878c',
    authDomain: 'e-commerce1-e878c.firebaseapp.com',
    storageBucket: 'e-commerce1-e878c.appspot.com',
    measurementId: 'G-206FCFR4WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa8yiLdTV4ySf9uiArz2RmZZRmDh32ogI',
    appId: '1:230612083597:android:198baa74da5316fce313c4',
    messagingSenderId: '230612083597',
    projectId: 'e-commerce1-e878c',
    storageBucket: 'e-commerce1-e878c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-X7twBOTPIm1ycNbQ5B4K27XzJGy84o',
    appId: '1:230612083597:ios:b4799c96710a5825e313c4',
    messagingSenderId: '230612083597',
    projectId: 'e-commerce1-e878c',
    storageBucket: 'e-commerce1-e878c.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );
}
